version: 2.0
jobs:
  test:
    working_directory: ~/rooms-booking
    environment:
      DATABASE_URL_TEST: postgres://ubuntu:@127.0.0.1:5432/room_booking_test
    docker:
      - image: circleci/ruby:2.3
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: ubuntu
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install -y --no-install-recommends build-essential libpq-dev curl git
      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum api/Gemfile.lock" }}
      - run:
          name: Install Ruby Dependencies
          command: cd api && bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 && cd ..
      - save_cache:
          key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum api/Gemfile.lock" }}
          paths:
            - api/vendor/bundle
      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: Run spec
          command: bundle exec rspec spec
          environment:
            RAILS_ENV: test
workflows:
  version: 2
  build-and-test:
    jobs:
      - test
