version: 2.0
jobs:
  build:
    working_directory: ~/rooms-booking
    environment:
      GOOGLE_PROJECT_ID: rooms-booking-177603
      GOOGLE_PROJECT_NAME: rooms-booking
      GOOGLE_CLUSTER_NAME: rooms-booking-staging
      GOOGLE_COMPUTE_ZONE: asia-northeast1-a
    docker:
      - image: circleci/ruby:2.3
        environment:
          RAILS_ENV: staging
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum api/Gemfile.lock" }}
      - run:
          name: Install Ruby Dependencies
          command: cd api && bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 && cd ..
      - save_cache:
          key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum api/Gemfile.lock" }}
          paths:
            - api/vendor/bundle
      - run:
          name: Install System Dependencies
          command: sudo apt-get update && sudo apt-get install -y --no-install-recommends build-essential libpq-dev
      - run:
          name: Install Google Cloud SDK
          command: |
            curl https://sdk.cloud.google.com | bash && \
              cat /opt/google-cloud-sdk/path.bash.inc | bash && \
              cat /opt/google-cloud-sdk/completion.bash.inc | bash && \
              /opt/google-cloud-sdk/bin/gcloud components install -q pubsub-emulator beta
      - run:
          name: Confirguration Google Cloud
          command: |
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update kubectl
            echo $GOOGLE_AUTH | base64 --decode -i > ${HOME}/gcloud-service-key.json

            sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set project $GOOGLE_PROJECT_ID
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set container/cluster $GOOGLE_CLUSTER_NAME

            # Reading the zone from the env var is not working so we set it here
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials $GOOGLE_CLUSTER_NAME
      - run:
          name: Build the api image
          command: |
            docker build -f ./api/Dockerfile.circleci.staging --rm=false -t ${GOOGLE_PROJECT_NAME}-api:$CIRCLE_SHA1 .
            docker tag ${GOOGLE_PROJECT_NAME}-api:$CIRCLE_SHA1 asia.gcr.io/${GOOGLE_PROJECT_ID}/${GOOGLE_PROJECT_NAME}-api:$CIRCLE_SHA1
  test:
    working_directory: ~/rooms-booking
    environment:
      ADMIN_EMAIL: dung.hoduy@asnet.com.vn
      ADMIN_NAME: Dung Ho
      SMTP_EMAIL: nw.testing02@gmail.com
      SMTP_PASSWORD: abcde12345-
      SMTP_HOST: localhost:3000
      DATABASE_URL_TEST: postgres://ubuntu:@127.0.0.1:5432/room_booking_test
    docker:
      - image: circleci/ruby:2.3
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: ubuntu
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum api/Gemfile.lock" }}
      - run:
          name: Install Ruby Dependencies
          command: cd api && bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 && cd ..
      - save_cache:
          key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum api/Gemfile.lock" }}
          paths:
            - api/vendor/bundle
      - run:
          name: Install System Dependencies
          command: sudo apt-get update && sudo apt-get install -y --no-install-recommends build-essential libpq-dev
      - run:
          name: Create DB
          command: cd api && bundle exec rake db:create db:schema:load --trace && cd ..
      - run:
          name: Run spec
          command: cd api && bundle exec rspec spec && cd ..
          environment:
            RAILS_ENV: test
  deploy:
    command: |
      if [ "${CIRCLE_BRANCH}" == "develop" ]; then
        sh ./deploy/staging/deploy.sh
      fi
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build

