version: '2'
services:
  postgres:
    image: postgres:9.6.4-alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  api:
    build: .
    env_file:
      - ./.env
    volumes:
      - .:/home/app
      - ./bundle:/bundle
    ports:
      - 3000:3000
    links:
      - postgres:db
