version: '2'
services:
  postgres:
    image: postgres:9.6.4-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  api:
    build: .
    container_name: api
    env_file:
      - .env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/home/app
      # - ./bundle:/bundle
    stdin_open: true
    ports:
      - 3000:3000
    links:
      - postgres:db
  redis:
    image: 'redis:3.2-alpine'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data

  sidekiq:
    depends_on:
      - postgres
      - redis
    build: .
    container_name: sidekiq
    env_file:
      - .env
    volumes:
      - .:/home/app
    command: bundle exec sidekiq
volumes:
  redis:
