version: '2'
services:
  postgres:
    image: postgres:9.6.4-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  api:
    build: .
    container_name: api
    env_file:
      - .env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/home/app
      # - ./bundle:/bundle
    stdin_open: true
    ports:
      - 3000:3000
    links:
      - postgres:db
