version: 2.0
jobs:
  build:
    working_directory: ~/rooms-booking
    environment:
      GOOGLE_PROJECT_ID: rooms-booking-177603
      GOOGLE_PROJECT_NAME: rooms-booking
      GOOGLE_CLUSTER_NAME: rooms-booking-staging
      GOOGLE_COMPUTE_ZONE: asia-northeast1-a
    docker:
      image: circleci/ruby:2.3
      image: circleci/postgres:9.6-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "./api/Gemfile.lock" }}
      - run: bundle install --path ./api/vendor/bundle
      - save_cache:
          key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "./api/Gemfile.lock" }}
          paths:
            - ./api/vendor/bundle
      - run:
          name: Update google cloud
          command: sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
      - run:
          name: Update kubectl
          command: sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update kubectl
      - run:
          name: Save google auth to file
          command: echo $GOOGLE_AUTH | base64 --decode -i > ${HOME}/gcloud-service-key.json
      - run:
          name: Set project id
          command: sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set project $GOOGLE_PROJECT_ID
      - run:
          name: Set container cluster
          command: sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set container/cluster $GOOGLE_CLUSTER_NAME
      - run:
          name: Set compute/zone
          command: sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: Get Credential
          command: sudo /opt/google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials $GOOGLE_CLUSTER_NAME
      - run:
          name: Build api image
          command: docker build -f ./api/Dockerfile.circleci.staging --rm=false -t ${GOOGLE_PROJECT_NAME}-api:$CIRCLE_SHA1 .
      - run:
          name: Tag api image
          command: docker tag ${GOOGLE_PROJECT_NAME}-api:$CIRCLE_SHA1 asia.gcr.io/${GOOGLE_PROJECT_ID}/${GOOGLE_PROJECT_NAME}-api:$CIRCLE_SHA1
  test:
    working_directory: ~/rooms-booking
    environment:
      GOOGLE_PROJECT_ID: rooms-booking-177603
      GOOGLE_PROJECT_NAME: rooms-booking
    docker:
      image: circleci/ruby:2.3
      image: circleci/postgres:9.6-alpine
    steps:
      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "./api/Gemfile.lock" }}
      - run:
          name: Run spec
          command: docker run asia.gcr.io/${GOOGLE_PROJECT_ID}/${GOOGLE_PROJECT_NAME}-api:$CIRCLE_SHA1 rspec
          environment:
            RAILS_ENV: test
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
