version: '2'
services:
  postgres:
    image: postgres:9.6.4-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  api-staging:
    build:
      context: ./../api
      dockerfile: Dockerfile.staging
    container_name: api-staging
    env_file:
      - .env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/home/app
    stdin_open: true
    ports:
      - 3000:3000
    links:
      - postgres:db
  proxy:
    build:
      context: ./nginx
      args:
        DOMAIN: dungho.tk
    container_name: nignx-ssl
    env_file:
      - ./.env
    volumes:
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-www:/var/www/letsencrypt
    links:
      - api-staging
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  job:
    build: ./../background
    container_name: job
    env_file:
      - ./../background/.env
    command: bundle exec sidekiq -r ./config/all_jobs.rb
    volumes:
      - ./../background:/home/app
    stdin_open: true
    links:
      - api
  redis:
    image: 'redis:3.2-alpine'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data
  sidekiq:
    depends_on:
      - redis
    build: ./../background
    container_name: sidekiq
    env_file:
      - ./../background/.env
    volumes:
      - ./../background:/home/app
    command: echo "job running..."
volumes:
  redis:
  letsencrypt-certs:
  letsencrypt-www:
