version: '2'
services:
  rabbitmq:
    build: rabbitmq
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
  postgres:
    image: postgres:9.6.4-alpine
    container_name: db
    env_file:
      - ./../api/.env
    ports:
      - 5432:5432
    volumes:
      - ./../api/db-data:/var/lib/postgresql/data
  api:
    build: ./../api
    container_name: api
    env_file:
      - ./../api/.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./../api:/home/app
    stdin_open: true
    ports:
      - 3000:3000
    links:
      - postgres:db
      - rabbitmq:amqp
  job:
    build: ./../background
    container_name: job
    env_file:
      - ./../background/.env
    command: ruby /home/app/bin/mywork
    volumes:
      - ./../background:/home/app
    stdin_open: true
    links:
      - api
      - rabbitmq:amqp

