version: '2'
services:
  postgres:
    image: postgres:9.6.4-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  api-staging:
    build:
      context: .
      dockerfile: Dockerfile-staging
    container_name: api-staging
    env_file:
      - .env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/home/app
    stdin_open: true
    ports:
      - 3000:3000
    links:
      - postgres:db
  job:
    build: ./../rb-background-job
    container_name: job
    env_file:
      - .env
    command: bundle exec sidekiq -r ./config/all_jobs.rb
    volumes:
      - ./../rb-background-job:/home/app
    stdin_open: true
    links:
      - api-staging
  redis:
    image: 'redis:3.2-alpine'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data
  sidekiq:
    depends_on:
      - redis
    build: ./../rb-background-job
    container_name: sidekiq
    env_file:
      - .env
    volumes:
      - ./../rb-background-job:/home/app
    command: echo "job running..."
volumes:
  redis:
