kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: rb-staging
  name: postgres-data
  labels:
    name: postgres-data
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  glusterfs:
    endpoints: glusterfs-cluster
    path: postgres-data

---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: rb-staging
  name: redis-data
  labels:
    name: redis-data
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: redis-data
