apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: rb-staging
  name: postgres
  labels:
    name: postgres
    project: rooms-booking
    environment: staging
spec:
  replicas: 1
  template:
    metadata:
      namespace: rb-staging
      name: postgres
      labels:
        name: postgres
        project: rooms-booking
        tier: database
        environment: staging
    spec:
      containers:
        # [START proxy_container]
        - image: gcr.io/cloudsql-docker/gce-proxy:1.09
          name: cloudsql-proxy
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=rooms-booking-177603:asia-northeast1:rb-postgresql-staging=tcp:0.0.0.0:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          ports:
            - name: port-db1
              containerPort: 5432
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
      # [END volumes]
---
apiVersion: v1
kind: Service
metadata:
  namespace: rb-staging
  name: postgres
  labels:
    name: postgres
    project: rooms-booking
    tier: database
    environment: staging
spec:
  selector:
    name: postgres
    project: rooms-booking
    tier: database
    environment: staging
  clusterIP: None
  ports:
    - port: 5432
      targetPort: port-db1
