apiVersion: batch/v1
kind: Job
metadata:
  namespace: rb-staging
  name: api-database-setup
spec:
  template:
    metadata:
      namespace: rb-staging
      name: api-database-setup
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      restartPolicy: Never
      containers:
      - name: api
        image: asia.gcr.io/booking-182401/booking-api:1.0
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ["bundle exec rake db:create && bundle exec rake db:migrate"]
        volumeMounts:
        - mountPath: "/home/app/.env"
          name: env
          subPath: api
        env:
          - name: POSTGRES_HOST
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
      volumes:
        - name: env
          configMap:
            name: env
