apiVersion: batch/v1
kind: Job
metadata:
  namespace: rb-staging
  name: api-database-setup
spec:
  template:
    metadata:
      namespace: rb-staging
      name: api-database-setup
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      restartPolicy: Never
      containers:
      - name: api
        image: asia.gcr.io/rooms-booking-177603/rooms-booking-api:1.0.2
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ["bundle exec rake db:create && bundle exec rake db:migrate"]
        volumeMounts:
        - mountPath: "/home/app/.env"
          name: env
          subPath: api
      volumes:
        - name: env
          configMap:
            name: env
