apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: rb-staging
  name: api
  labels:
    name: api
    project: rooms-booking
    environment: staging
spec:
  replicas: 1
  template:
    metadata:
      namespace: rb-staging
      name: api
      labels:
        name: api
        project: rooms-booking
        tier: backend
        environment: staging
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: api
        image: asia.gcr.io/rooms-booking-177603/rooms-booking-api:1.0.2
        imagePullPolicy: Always
        command: ["/bin/sh", -c]
        args: ["bundle exec puma -C config/puma.rb"]
        ports:
          - containerPort: 3000
        volumeMounts:
        - mountPath: "/home/app/.env"
          name: env
          subPath: api
      volumes:
        - name: env
          configMap:
            name: env

---
apiVersion: v1
kind: Service
metadata:
  namespace: rb-staging
  name: api
  labels:
    name: api
    project: rooms-booking
    tier: loadbalancer
    environment: staging
spec:
  selector:
    name: api
    project: rooms-booking
    tier: backend
    environment: staging
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
