apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: rb-staging
  name: background-job
  labels:
    name: background-job
    project: rooms-booking
    environment: staging
spec:
  replicas: 1
  template:
    metadata:
      namespace: rb-staging
      name: background-job
      labels:
        name: background-job
        project: rooms-booking
        tier: backend
        environment: staging
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: background-job
        image: asia.gcr.io/booking-182401/booking-job:latest
        imagePullPolicy: Always
        command: ["/bin/sh", -c]
        args: ["rake sneakers:run --require /home/app/app/jobs/jobs.rb"]
        volumeMounts:
        - mountPath: "/home/app/.env"
          name: env
          subPath: api
      volumes:
        - name: env
          configMap:
            name: env
