source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'dotenv-rails'
gem 'validates_timeliness', '~> 4.0'
gem 'devise'

# A pure ruby implementation of the RFC 7519 OAuth JSON Web Token (JWT) standard.
gem 'jwt'

gem 'omniauth-gitlab'
gem 'omniauth-google-oauth2', '~> 0.4.1'

# versioning Rails based RESTful APIs
gem 'versionist'

# Object oriented authorization for Rails applications
gem 'pundit', '~> 1.1'

# encapsulates the JSON serialization of objects
gem "active_model_serializers"

# service object
gem 'simple_command'

# A Scope & Engine based, clean, powerful, customizable and sophisticated paginator for modern web app frameworks and ORMs
gem 'kaminari'

# counter_culture provides turbo-charged counter caches
gem 'counter_culture', '~> 1.7'

gem 'rails_param'

gem "bunny", ">= 2.7.0"
gem 'mailgun-ruby', '~>1.1.6'

gem 'state_machines-activerecord'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri

  # Code coverage for Ruby
  gem 'simplecov', '~> 0.12.0'
  gem 'rspec-rails', '~> 3.6'
end

group :test do
  gem 'factory_girl_rails', '~> 4.7'
  gem 'faker'
  gem 'database_cleaner'

  # gem 'shoulda-matchers', '~> 3.1'
  gem 'shoulda-matchers', git: 'https://github.com/thoughtbot/shoulda-matchers.git', branch: 'rails-5'

  # Provide rspec matchers to match http response code
  gem 'response_code_matchers', '~> 0.1.0'

  gem 'shoulda-callback-matchers'
  gem 'pundit-matchers', '~> 1.3.1', require: false
  gem 'email_spec'
  gem 'timecop'
  gem 'bunny-mock'
end

group :development do
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  # N+1 query detect
  gem 'bullet'
  # API documentation
  gem 'swagger-docs'
  gem 'annotate', require: false
end

